/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/index/index" |
       "/pages/about/about" |
       "/pages/annotation/annotationDetail" |
       "/pages/annotation/annotationList" |
       "/pages/demo/demo" |
       "/pages/demo/form" |
       "/pages/demo/indexBar" |
       "/pages/demo/selectPicker" |
       "/pages/demo/tree" |
       "/pages/login/login" |
       "/pages/login/loginOauth2" |
       "/pages/message/message" |
       "/pages/more/more" |
       "/pages/user/people" |
       "/pages/workHome/workHome" |
       "/pages-home/home/home" |
       "/pages-message/chat/chat" |
       "/pages-message/chat/chatSetting" |
       "/pages-message/contacts/contacts" |
       "/pages-message/moreFunction/moreFunction" |
       "/pages-message/myGroup/addGroup" |
       "/pages-message/myGroup/groupPage" |
       "/pages-message/myGroup/myGroup" |
       "/pages-message/personPage/personPage" |
       "/pages-message/tenant/tenant" |
       "/pages-user/location/location" |
       "/pages-user/organization/organization" |
       "/pages-user/userDetail/userDetail" |
       "/pages-user/userEdit/userEdit" |
       "/pages-work/dragPage/index" |
       "/pages-work/onlinePage/onlineAdd" |
       "/pages-work/onlinePage/onlineDetail" |
       "/pages-work/onlinePage/onlineEdit" |
       "/pages-sub/online/online" |
       "/pages-sub/online/onlineCard" |
       "/pages-sub/online/onlineTable" |
       "/pages-homeai/pages/family/index" |
       "/pages-homeai/pages/index/index" |
       "/pages-homeai/pages/profile/index" |
       "/pages-homeai-ai/ai/chat" |
       "/pages-homeai-ai/ai/conversations" |
       "/pages-homeai-more/bill/add" |
       "/pages-homeai-more/bill/index" |
       "/pages-homeai-more/bill/statistics" |
       "/pages-homeai-more/learn/index" |
       "/pages-homeai-more/plan/add" |
       "/pages-homeai-more/plan/index" |
       "/pages-homeai-more/recipe/add" |
       "/pages-homeai-more/recipe/detail" |
       "/pages-homeai-more/recipe/index" |
       "/pages-homeai-more/storage/files" |
       "/pages-homeai-more/storage/index" |
       "/pages-homeai-more/storage/office-convert" |
       "/pages-homeai-more/storage/office-generate" |
       "/pages-homeai-more/storage/office-history" |
       "/pages-homeai-more/storage/search";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/message/message" | "/pages/index/index" | "/pages/user/people"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
