/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/launch/index" |
       "/pages/agreement/index" |
       "/pages/auth/change-password" |
       "/pages/auth/login" |
       "/pages/auth/profile-edit" |
       "/pages/homeai/family" |
       "/pages/homeai/index" |
       "/pages/homeai/profile" |
       "/pages/privacy/index" |
       "/pages-homeai-ai/ai/chat" |
       "/pages-homeai-ai/ai/conversations" |
       "/pages-homeai-more/all-functions/index" |
       "/pages-homeai-more/bill/add" |
       "/pages-homeai-more/bill/edit" |
       "/pages-homeai-more/bill/import-confirm" |
       "/pages-homeai-more/bill/import" |
       "/pages-homeai-more/bill/index" |
       "/pages-homeai-more/bill/statistics" |
       "/pages-homeai-more/learn/add" |
       "/pages-homeai-more/learn/detail" |
       "/pages-homeai-more/learn/index" |
       "/pages-homeai-more/learn/record" |
       "/pages-homeai-more/plan/add" |
       "/pages-homeai-more/plan/detail" |
       "/pages-homeai-more/plan/index" |
       "/pages-homeai-more/recipe/add" |
       "/pages-homeai-more/recipe/category" |
       "/pages-homeai-more/recipe/detail" |
       "/pages-homeai-more/recipe/index" |
       "/pages-homeai-more/storage/files" |
       "/pages-homeai-more/storage/index" |
       "/pages-homeai-more/storage/office-convert" |
       "/pages-homeai-more/storage/office-generate" |
       "/pages-homeai-more/storage/office-history" |
       "/pages-homeai-more/storage/preview" |
       "/pages-homeai-more/storage/recycle" |
       "/pages-homeai-more/storage/search" |
       "/pages-homeai-more/storage/StorageBrowser";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/homeai/index" | "/pages/homeai/family" | "/pages/homeai/profile"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
